# Deployment da app web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-tem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-tem
  template:
    metadata:
      labels:
        app: conv-tem
    spec:
      containers:
      - name: conv-tem
        image: guimap/conversao-temperatura:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conv-tem
spec:
  selector:
    app: conv-tem
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer